FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.24 as builder

WORKDIR /workspace

COPY thanos .

ENV CGO_ENABLED=0

# Install promu and build thanos
ARG TARGETOS TARGETARCH
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -tags -netgo $GOFLAGS -o /go/bin/thanos ./cmd/thanos

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:759f5f42d9d6ce2a705e290b7fc549e2d2cd39312c4fa345f93c02e4abb8da95
WORKDIR /

COPY --from=builder /go/bin/thanos /bin/thanos
COPY --from=builder /workspace/LICENSE /licenses/.

USER nobody
ENTRYPOINT [ "/bin/thanos" ]

ARG VERSION=v0.39.2
LABEL com.redhat.component="coo-thanos-container" \
      name="rhobs/thanos" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/openshift/thanos" \
      summary="Thanos for Cluster Observability Operator" \
      io.openshift.expose-services="" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="COO Thanos" \
      io.k8s.description="Thanos extends Prometheus with highly available, scalable and unlimited metric storage." \
      maintainer="team-monitoring@redhat.com" \
      description="Thanos for Cluster Observability Operator"
