FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.24 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY observability-operator/ .

ENV GOFLAGS='-mod=mod'
ENV CGO_ENABLED=1

# Build
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -a -tags netgo,osusergo -o manager cmd/operator/main.go

FROM registry.redhat.io/openshift4/ose-cli-rhel9 AS origincli

RUN OC_PATH=$(which oc); \
    echo ${OC_PATH}; \
    cp ${OC_PATH} /tmp/oc

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:759f5f42d9d6ce2a705e290b7fc549e2d2cd39312c4fa345f93c02e4abb8da95
WORKDIR /

# skip, only needed for must gather
# RUN microdnf install -y rsync tar xz

COPY --from=origincli /tmp/oc /usr/bin/oc

COPY --from=builder /workspace/manager .
COPY --from=builder --chmod=0755 /workspace/must-gather/collection-scripts/* /usr/bin/
COPY --from=builder /workspace/LICENSE      /licenses/.
USER 65532:65532

ENTRYPOINT ["/manager"]

ARG VERSION=v1.3.1
LABEL com.redhat.component="coo-operator" \
      name="Cluster Observability Operator" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/rhobs/observability-operator" \
      summary="Cluster Observability Operator" \
      io.openshift.tags="openshift,observability" \
      io.k8s.display-name="Cluster Observability Operator" \
      io.k8s.description="Cluster Observability Operator enables administrators to create standalone monitoring stacks that are independently configurable for use by different services and users." \
      maintainer="Cluster Observability Operator Team <team-monitoring-incluster@redhat.com>" \
      description="Cluster Observability Operator"
