FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.24 as builder
WORKDIR /workspace

# Copy source files
COPY obo-prometheus-operator/ .

ENV GOFLAGS='-mod=mod'
ENV CGO_ENABLED=0

# Build
RUN make admission-webhook

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71

COPY --from=builder workspace/admission-webhook /bin/admission-webhook
COPY --from=builder /workspace/LICENSE      /licenses/.

USER nobody

ENTRYPOINT ["/bin/admission-webhook"]

LABEL com.redhat.component="coo-po-admission-webhook" \
      name="prometheus-operator-admission-webhook" \
      version="v0.86.1" \
      summary="Admission Webhook for Prometheus Operator" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="Admission Webhook for Prometheus Operator" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      maintainer="Admission Webhook for Prometheus Operator" \
      description="Admission Webhook for Prometheus Operator" \
      io.k8s.description="Admission Webhook for Prometheus Operator"
