# Builder
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:bb08f2300cb8d12a7eb91dddf28ea63692b3ec99e7f0fa71a1b300f2756ea829 as builder

USER root

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install -y python3 python3-pyyaml

WORKDIR /workspace

COPY /observability-operator/bundle/ bundle
COPY /observability-operator/LICENSE LICENSE
COPY /bundle-patches/render_templates .

# Get yq from konflux CI
FROM quay.io/konflux-ci/yq@sha256:d4feadf33854f9d9aef4e7deed45ba61d4c69d3fc2a685e82ad8ba12fc8bbae1 AS parser

# Run template rendering
FROM builder as final

COPY --from=parser /usr/bin/yq /usr/local/bin/yq

RUN chmod +x /usr/local/bin/yq

ARG REGISTRY=quay.io/redhat-user-workloads
ENV REGISTRY=${REGISTRY}

RUN mv bundle/manifests/observability-operator.clusterserviceversion.yaml bundle/manifests/cluster-observability-operator.clusterserviceversion.yaml && \
    echo "Renamed file successfully." && \
    echo "Running render_templates..." && \
    ./render_templates bundle/manifests/cluster-observability-operator.clusterserviceversion.yaml bundle/metadata/annotations.yaml && \
    echo "Rendered annotations.yaml successfully." && \
    echo "Contents of annotations.yaml:" && \
    cat bundle/metadata/annotations.yaml

# Final image
FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=cluster-observability-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.37.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=unknown

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

ARG VERSION=v1.3.1
LABEL com.redhat.component="coo-bundle" \
      name="cluster-observability-operator/cluster-observability-operator-bundle" \
      cpe="cpe:/a:redhat:cluster_observability_operator:1.3::el9" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/rhobs/observability-operator" \
      summary="Cluster Observability Operator Bundle" \
      com.redhat.openshift.versions="v4.12" \
      io.openshift.tags="openshift,observability,monitoring" \
      io.k8s.display-name="Cluster Observability Operator Bundle" \
      io.k8s.description="Cluster Observability Operator Bundle" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      description="Cluster Observability Operator Bundle"

COPY --from=final /workspace/bundle/manifests /manifests/
COPY --from=final /workspace/bundle/metadata /metadata/
COPY --from=final /workspace/bundle/tests/scorecard /tests/scorecard/
COPY --from=final /workspace/LICENSE /licenses/.
