FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 as builder
USER root

RUN dnf install -y --setopt=tsflags=nodocs mailcap && \
    dnf clean all && \
    rm -rf /var/cache/dnf

WORKDIR /app

COPY perses/ .

ENV GOFLAGS="-mod=readonly"
RUN go mod download

RUN mkdir /plugins

RUN make build-api
RUN make build-cli

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71

LABEL maintainer="Observability UI team <team-observability-ui@redhat.com>"

COPY --from=builder  /app/bin/perses                         /bin/perses
COPY --from=builder  /app/bin/percli                         /bin/percli
COPY --from=builder  /app/docs/examples/config.docker.yaml   /etc/perses/config.yaml
COPY --from=builder  /app/plugins-archive/                   /etc/perses/plugins-archive/
COPY --from=builder  /app/LICENSE                            /LICENSE
COPY --from=builder  /plugins                                /etc/perses/plugins
COPY --from=builder  /etc/mime.types                         /etc/mime.types

RUN chgrp -R 0 /etc/perses && \
    chmod -R g=u /etc/perses

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", "--log.level=error"]

ARG VERSION=v0.51.1
LABEL com.redhat.component="coo-perses" \
    name="perses/perses" \
    version="${VERSION}" \
    release="${VERSION}" \
    vendor="Red Hat, Inc." \
    distribution-scope="public" \
    url="https://github.com/rhobs/perses" \
    summary="Perses for Cluster Observability Operator" \
    io.openshift.tags="openshift,observability-ui,perses" \
    io.k8s.display-name="Perses for Cluster Observability Operator" \
    io.k8s.description="Perses for Cluster Observability Operator" \
    maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
    description="Perses for Cluster Observability Operator"
