# Builder
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:69f5c9886ecb19b23e88275a5cd904c47dd982dfa370fbbd0c356d7b1047ef68 as builder

USER root

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install -y python3 python3-pyyaml

WORKDIR /workspace

COPY /observability-operator/bundle/ bundle
COPY /observability-operator/LICENSE LICENSE
COPY /bundle-patches/render_templates .

# Get yq from konflux CI
FROM quay.io/konflux-ci/yq@sha256:0aabca8d3b8a634a246e084c0d9b8762bf5cce0d592bc016f6aff5a37220eff2 AS parser

# Run template rendering
FROM builder as final

COPY --from=parser /usr/bin/yq /usr/local/bin/yq

RUN chmod +x /usr/local/bin/yq

ARG REGISTRY=quay.io/redhat-user-workloads
ENV REGISTRY=${REGISTRY}

RUN mv bundle/manifests/observability-operator.clusterserviceversion.yaml bundle/manifests/cluster-observability-operator.clusterserviceversion.yaml && \
    echo "Renamed file successfully." && \
    echo "Running render_templates..." && \
    ./render_templates bundle/manifests/cluster-observability-operator.clusterserviceversion.yaml bundle/metadata/annotations.yaml && \
    echo "Rendered annotations.yaml successfully." && \
    echo "Contents of annotations.yaml:" && \
    cat bundle/metadata/annotations.yaml

# Final image
FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=cluster-observability-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.37.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=unknown

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

ARG VERSION=v1.4.0
LABEL com.redhat.component="coo-bundle" \
      name="cluster-observability-operator/cluster-observability-operator-bundle" \
      cpe="cpe:/a:redhat:cluster_observability_operator:1.4::el9" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/rhobs/observability-operator" \
      summary="Cluster Observability Operator Bundle" \
      com.redhat.openshift.versions="v4.12" \
      io.openshift.tags="openshift,observability,monitoring" \
      io.k8s.display-name="Cluster Observability Operator Bundle" \
      io.k8s.description="Cluster Observability Operator Bundle" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      description="Cluster Observability Operator Bundle"

COPY --from=final /workspace/bundle/manifests /manifests/
COPY --from=final /workspace/bundle/metadata /metadata/
COPY --from=final /workspace/bundle/tests/scorecard /tests/scorecard/
COPY --from=final /workspace/LICENSE /licenses/.
