FROM registry.redhat.io/ubi9/nodejs-20:latest AS web-builder

USER 0

WORKDIR /workspace

COPY alertmanager/ .

RUN make build-react-app assets-compress

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.22 AS builder

WORKDIR /workspace

COPY --from=web-builder /workspace/ .

ENV GOFLAGS='-mod=mod -tags=netgo'
ENV CGO_ENABLED=0
ENV NO_DOCKER=true
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build $GOFLAGS -o alertmanager github.com/prometheus/alertmanager/cmd/alertmanager
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build $GOFLAGS -o amtool github.com/prometheus/alertmanager/cmd/amtool

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:759f5f42d9d6ce2a705e290b7fc549e2d2cd39312c4fa345f93c02e4abb8da95

COPY --from=builder workspace/amtool       /bin/amtool
COPY --from=builder workspace/alertmanager /bin/alertmanager
COPY --from=builder workspace/examples/ha/alertmanager.yml      /etc/alertmanager/alertmanager.yml
COPY --from=builder workspace/LICENSE      /licenses/.

RUN mkdir -p /alertmanager && \
    chown -R nobody:nobody etc/alertmanager /alertmanager

USER       nobody
EXPOSE     9093
VOLUME     [ "/alertmanager" ]
WORKDIR    /alertmanager
ENTRYPOINT [ "/bin/alertmanager" ]
CMD        [ "--config.file=/etc/alertmanager/alertmanager.yml", \
             "--storage.path=/alertmanager" ]

ARG VERSION=v0.28.1 
LABEL com.redhat.component="coo-alertmanager" \           
      name="cluster-observability-operator/alertmanager-rhel9" \
      cpe="cpe:/a:redhat:cluster_observability_operator:1.4::el9" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/prometheus/alertmanager" \
      summary="Alertmanager for Cluster Observability Operator" \
      io.openshift.tags="openshift,monitoring" \
      io.k8s.display-name="Alertmanager" \
      io.k8s.description="Alertmanager handles alerts sent by client applications such as the Prometheus server" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      description="Alertmanager for Cluster Observability Operator"
