FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.24 as builder
WORKDIR /workspace

# Copy source files
COPY obo-prometheus-operator/ .

ENV GOFLAGS='-mod=mod'
ENV CGO_ENABLED=0

# Build
RUN make admission-webhook

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:759f5f42d9d6ce2a705e290b7fc549e2d2cd39312c4fa345f93c02e4abb8da95

COPY --from=builder workspace/admission-webhook /bin/admission-webhook
COPY --from=builder /workspace/LICENSE      /licenses/.

USER nobody

ENTRYPOINT ["/bin/admission-webhook"]

ARG VERSION=v0.87.0
LABEL com.redhat.component="coo-po-admission-webhook" \
      name="cluster-observability-operator/obo-prometheus-operator-admission-webhook-rhel9" \
      cpe="cpe:/a:redhat:cluster_observability_operator:1.4::el9" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/rhobs/obo-prometheus-operator" \
      summary="Admission Webhook for Prometheus Operator" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="Admission Webhook for Prometheus Operator" \
      io.k8s.description="Admission Webhook for Prometheus Operator" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      description="Admission Webhook for Prometheus Operator"
