# Builder
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:2f06ae0e6d3d9c4f610d32c480338eef474867f435d8d28625f2985e8acde6e8 as builder

USER root

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install -y python3 python3-pyyaml

WORKDIR /workspace

COPY /observability-operator/bundle/ bundle
COPY /observability-operator/LICENSE LICENSE
COPY /bundle-patches/render_templates .

# Get yq from konflux CI
FROM quay.io/konflux-ci/yq@sha256:7ef2e2f76ca36bdc7eb9203df31f3bce546d1267b969d9bd2691094b88610dbb AS parser

# Run template rendering
FROM builder as final

COPY --from=parser /usr/bin/yq /usr/local/bin/yq

RUN chmod +x /usr/local/bin/yq

ARG REGISTRY=quay.io/redhat-user-workloads
ENV REGISTRY=${REGISTRY}

RUN mv bundle/manifests/observability-operator.clusterserviceversion.yaml bundle/manifests/cluster-observability-operator.clusterserviceversion.yaml && \
    echo "Renamed file successfully." && \
    echo "Running render_templates..." && \
    ./render_templates bundle/manifests/cluster-observability-operator.clusterserviceversion.yaml bundle/metadata/annotations.yaml && \
    echo "Rendered annotations.yaml successfully." && \
    echo "Contents of annotations.yaml:" && \
    cat bundle/metadata/annotations.yaml

# Final image
FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=cluster-observability-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.37.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=unknown

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL com.redhat.component="coo-bundle" \
      name="cluster-observability-operator-bundle" \
      release="v1.2.2" \
      version="v1.2.2" \
      com.redhat.openshift.versions="v4.12" \
      distribution-scope="public" \
      summary="Cluster Observability Operator Bundle" \
      io.openshift.tags="openshift,observability,monitoring" \
      io.k8s.display-name="Cluster Observability Operator Bundle" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      description="Cluster Observability Operator Bundle" \
      io.k8s.description="Cluster Observability Operator Bundle" \
      url="https://github.com/rhobs/observability-operator"\
      vendor="Red Hat, Inc."

COPY --from=final /workspace/bundle/manifests /manifests/
COPY --from=final /workspace/bundle/metadata /metadata/
COPY --from=final /workspace/bundle/tests/scorecard /tests/scorecard/
COPY --from=final /workspace/LICENSE /licenses/.

