FROM registry.redhat.io/ubi9/nodejs-20:latest AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0
COPY ui-logging-pf4/web/package*.json web/
COPY ui-logging-pf4/Makefile Makefile
RUN cd web && npm ci --omit=optional --ignore-scripts

COPY ui-logging-pf4/web/ web/
RUN make build-frontend

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.22 as go-builder

WORKDIR /opt/app-root

COPY ui-logging-pf4/Makefile Makefile
COPY ui-logging-pf4/go.mod go.mod
COPY ui-logging-pf4/go.sum go.sum

RUN make install-backend

COPY ui-logging-pf4/config/ config/
COPY ui-logging-pf4/cmd/ cmd/
COPY ui-logging-pf4/pkg/ pkg/

ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

RUN make build-backend BUILD_OPTS="-tags strictfipsruntime"

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:90bd85dcd061d1ad6dbda70a867c41958c04a86462d05c631f8205e8870f28f8

RUN mkdir /licenses
COPY ui-logging-pf4/LICENSE /licenses/.

USER 1001

COPY --from=web-builder /opt/app-root/web/dist /opt/app-root/web/dist
COPY --from=go-builder /opt/app-root/plugin-backend /opt/app-root
COPY ui-logging-pf4/config /opt/app-root/config

ENTRYPOINT ["/opt/app-root/plugin-backend", "-config-path", "/opt/app-root/config", "-static-path", "/opt/app-root/web/dist"]

ARG VERSION=v6.0.0
LABEL com.redhat.component="coo-logging-console-plugin" \
      name="openshift/logging-console-plugin" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/openshift/logging-view-plugin" \
      summary="OpenShift console plugin to view and explore logs" \
      io.openshift.tags="openshift,observability-ui,logging" \
      io.k8s.display-name="OpenShift console logging plugin" \
      io.k8s.description="OpenShift console plugin to view and explore logs" \
      maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
      description="OpenShift console plugin to view and explore logs"
