FROM registry.redhat.io/ubi9/nodejs-22:latest AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0
COPY ui-monitoring/web/package*.json web/
COPY ui-monitoring/Makefile Makefile
RUN cd web && npm ci --legacy-peer-deps --omit=optional --ignore-scripts

COPY ui-monitoring/web/ web/
COPY ui-monitoring/config/ config/
COPY ui-monitoring/scripts/update-plugin-name.sh scripts/update-plugin-name.sh
RUN make update-plugin-name
ENV I18N_NAMESPACE="plugin__monitoring-console-plugin"
RUN make build-frontend

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.24 as go-builder

WORKDIR /opt/app-root

COPY ui-monitoring/Makefile Makefile
COPY ui-monitoring/go.mod go.mod
COPY ui-monitoring/go.sum go.sum

RUN make install-backend

COPY ui-monitoring/cmd/ cmd/
COPY ui-monitoring/pkg/ pkg/

ENV GOOS=${TARGETOS:-linux}
ENV GOARCH=${TARGETARCH}
ENV GOEXPERIMENT=strictfipsruntime
ENV GOFLAGS=-mod=readonly
ENV CGO_ENABLED=1

RUN make build-backend

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:90bd85dcd061d1ad6dbda70a867c41958c04a86462d05c631f8205e8870f28f8

RUN mkdir /licenses
COPY ui-monitoring/LICENSE /licenses/.

USER 1001

COPY --from=web-builder /opt/app-root/web/dist /opt/app-root/web/dist
COPY --from=go-builder /opt/app-root/plugin-backend /opt/app-root
COPY --from=web-builder /opt/app-root/config /opt/app-root/config

ENTRYPOINT ["/opt/app-root/plugin-backend", "-static-path", "/opt/app-root/web/dist"]

ARG VERSION=v0.5.0
LABEL com.redhat.component="coo-monitoring-console-plugin" \
      name="openshift/monitoring-console-plugin" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/openshift/monitoring-plugin" \
      summary="OpenShift monitoring plugin to view and explore metrics and alerts" \
      io.openshift.tags="openshift,observability-ui,metrics,alerts" \
      io.k8s.display-name="OpenShift console monitoring plugin" \
      io.k8s.description="OpenShift monitoring plugin to view and explore metrics and alerts" \
      maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
      description="OpenShift monitoring plugin to view and explore metrics and alerts"
