FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 as builder
WORKDIR /workspace

# Copy source files
COPY obo-prometheus-operator/ .

ENV GOFLAGS='-mod=mod'

ENV GOTOOLCHAIN=local
ENV CGO_ENABLED=1
ENV GOEXPERIMENT=strictfipsruntime

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build $GOFLAGS -o operator ./cmd/operator/

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:69f5c9886ecb19b23e88275a5cd904c47dd982dfa370fbbd0c356d7b1047ef68

COPY --from=builder /workspace/operator /bin/operator
COPY --from=builder /workspace/LICENSE      /licenses/.

# On busybox 'nobody' has uid `65534'
USER 65534

ARG VERSION=v0.89.0
LABEL com.redhat.component="coo-prometheus-operator" \
      name="cluster-observability-operator/obo-prometheus-rhel9-operator" \
      cpe="cpe:/a:redhat:cluster_observability_operator:1.4::el9" \
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/rhobs/obo-prometheus-operator" \
      summary="Prometheus Operator" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="Prometheus Operator" \
      io.k8s.description="COO Prometheus Operator" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      description="Prometheus Operator"

ENTRYPOINT ["/bin/operator"]
