FROM registry.redhat.io/ubi9/nodejs-20:latest AS web-builder

USER 0

WORKDIR /workspace

COPY prometheus/ .

RUN make assets-compress

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 AS builder

WORKDIR /workspace

# RUN microdnf install -y bzip2 jq && microdnf clean all

COPY --from=web-builder /workspace/ .

ENV GOFLAGS='-mod=mod -tags=builtinassets,netgo,stringlabels'
ENV CGO_ENABLED=0
# Build prometheus directly using Go
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build $GOFLAGS -o ./prometheus ./cmd/prometheus
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build $GOFLAGS -o ./promtool ./cmd/promtool

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:bb08f2300cb8d12a7eb91dddf28ea63692b3ec99e7f0fa71a1b300f2756ea829

COPY --from=builder /workspace/prometheus                            /bin/prometheus
COPY --from=builder /workspace/promtool                              /bin/promtool
COPY --from=builder /workspace/documentation/examples/prometheus.yml /etc/prometheus/prometheus.yml
COPY --from=builder /workspace/LICENSE      /licenses/.


RUN mkdir -p /prometheus \
    && chgrp -R 0 /etc/prometheus /prometheus \
    && chmod -R g=u /etc/prometheus /prometheus

USER       nobody
EXPOSE     9090
WORKDIR    /prometheus
VOLUME     ["/prometheus"]
ENTRYPOINT ["/bin/prometheus"]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus" ]

ARG VERSION=v3.7.2
LABEL com.redhat.component="coo-prometheus-container" \
      name="cluster-observability-operator/prometheus-rhel9"
      version="${VERSION}" \
      release="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/prometheus/prometheus" \
      summary="Prometheus for Cluster Observability Operator" \
      io.openshift.expose-services="" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="COO Prometheus" \
      io.k8s.description="Prometheus is a CNCF project that collects metrics, evaluates rules and triggers alerts." \
      maintainer="team-monitoring@redhat.com" \
      description="Prometheus for Cluster Observability Operator"
