FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 as builder
USER root

RUN dnf install -y --setopt=tsflags=nodocs mailcap && \
    dnf clean all && \
    rm -rf /var/cache/dnf

WORKDIR /app

COPY perses/ .

ENV GOFLAGS="-mod=readonly"
RUN go mod download
RUN make build-api 
RUN make build-cli

FROM registry.redhat.io/rhel9-4-els/rhel:9.4

LABEL maintainer="Observability UI team <team-observability-ui@redhat.com>"

USER 1001

COPY --from=builder --chown=nobody:nobody /app/bin/perses                         /bin/perses
COPY --from=builder --chown=nobody:nobody /app/bin/percli                         /bin/percli
COPY --from=builder --chown=nobody:nobody /app/docs/examples/config.docker.yaml   /etc/perses/config.yaml
COPY --from=builder --chown=nobody:nobody /app/cue/schemas                        /etc/perses/cue/schemas
COPY --from=builder --chown=nobody:nobody /app/cue.mod                            /etc/perses/cue.mod
COPY --from=builder --chown=nobody:nobody /app/LICENSE                            /LICENSE
COPY --from=builder --chown=nobody:nobody /etc/mime.types                         /etc/mime.types

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", "--log.level=error"]

LABEL com.redhat.component="coo-perses" \
    name="perses/perses" \
    version="v0.50.3" \
    summary="Perses for Cluster Observability Operator" \
    io.openshift.tags="openshift,observability-ui,perses" \
    io.k8s.display-name="Perses for Cluster Observability Operator" \
    io.k8s.description="Perses for Cluster Observability Operator" \
    maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
    description="Perses for Cluster Observability Operator"
