FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.24 as builder
WORKDIR /workspace

# Copy source files
COPY obo-prometheus-operator/ .

ENV GOFLAGS='-mod=mod'
ENV CGO_ENABLED=0

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build $GOFLAGS -o operator ./cmd/operator/

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71

COPY --from=builder /workspace/operator /bin/operator
COPY --from=builder /workspace/LICENSE      /licenses/.

# On busybox 'nobody' has uid `65534'
USER 65534

LABEL com.redhat.component="coo-prometheus-operator" \
      name="prometheus-operator" \
      version="v0.86.1" \
      summary="Prometheus Operator" \
      io.openshift.tags="monitoring" \
      io.k8s.display-name="Prometheus Operator" \
      io.k8s.description="COO Prometheus Operator" \
      maintainer="OpenShift Monitoring team <team-monitoring-incluster@redhat.com>" \
      maintainer="Prometheus Operator" \
      description="Prometheus Operator"

ENTRYPOINT ["/bin/operator"]
