FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 as builder

USER root

RUN dnf install -y --setopt=tsflags=nodocs mailcap && \
    dnf clean all && \
    rm -rf /var/cache/dnf

WORKDIR /app

COPY perses-operator/ .

RUN make bin

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:bb08f2300cb8d12a7eb91dddf28ea63692b3ec99e7f0fa71a1b300f2756ea829

LABEL maintainer="Observability UI team <team-observability-ui@redhat.com>"

USER nobody

COPY --from=builder --chown=nobody:nobody /app/bin/manager  /bin/manager
COPY --from=builder --chown=nobody:nobody /app/LICENSE      /LICENSE
COPY --from=builder --chown=nobody:nobody /etc/mime.types   /etc/mime.types

EXPOSE     8080
ENTRYPOINT [ "/bin/manager" ]

ARG VERSION=v0.2.0
LABEL com.redhat.component="coo-perses-operator" \
    name="cluster-observability-operator/perses-rhel9-operator"
    version="${VERSION}" \
    release="${VERSION}" \
    vendor="Red Hat, Inc." \
    distribution-scope="public" \
    url="https://github.com/rhobs/perses-operator" \
    summary="Perses Operator for Cluster Observability Operator" \
    io.openshift.tags="openshift,observability-ui,perses-operator" \
    io.k8s.display-name="Perses Operator for Cluster Observability Operator" \
    io.k8s.description="Perses Operator for Cluster Observability Operator" \
    maintainer="Observability UI Team <team-observability-ui@redhat.com>" \
    description="Perses Operator for Cluster Observability Operator"
