---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: coo-fbc-v4-18-20260526-213924-000-2026-05-26-17-58
  namespace: cluster-observabilit-tenant
spec:
  releasePlan: coo-fbc-v4-18-staging-release-plan
  snapshot: coo-fbc-v4-18-20260526-213924-000
  data:
    releaseNotes:
      type: RHBA
      topic: 'Cluster Observability Operator 1.5.0 release - fbc 4.18 - staging.'
      references:
        - https://access.redhat.com/security/updates/classification
