---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: coo-fbc-v4-20-20260312-200519-000-2026-03-12-16-19
  namespace: cluster-observabilit-tenant
spec:
  releasePlan: coo-fbc-v4-20-staging-release-plan
  snapshot: coo-fbc-v4-20-20260312-200519-000
  data:
    releaseNotes:
      type: RHBA
      topic: 'Cluster Observability Operator 1.4.0 release - fbc 4.20 - staging.'
      references:
        - https://access.redhat.com/security/updates/classification
