---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: coo-fbc-v4-16-20260306-205443-000-2026-03-06-16-11
  namespace: cluster-observabilit-tenant
spec:
  releasePlan: coo-fbc-v4-16-staging-release-plan
  snapshot: coo-fbc-v4-16-20260306-205443-000
  data:
    releaseNotes:
      type: RHBA
      topic: 'Cluster Observability Operator 1.4.0 release - fbc 4.16 - staging.'
      references:
        - https://access.redhat.com/security/updates/classification
