---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: coo-fbc-v4-14-8tbmp-2025-07-17-15-41
  namespace: cluster-observabilit-tenant
spec:
  releasePlan: coo-fbc-v4-14-staging-release-plan
  snapshot: coo-fbc-v4-14-8tbmp
  data:
    releaseNotes:
      type: RHBA
      topic: 'Cluster Observability Operator 1.2.2 release - fbc 4.14 - staging.'
      issues:
        fixed:
          - id: COO-1062
            source: issues.redhat.com
      references:
        - https://access.redhat.com/security/updates/classification
